### ISSUE TITLE
 yarn add scikitjs fail

### ISSUE THREAD

**Issue by condorman** [javascriptdata/scikit.js#192]
1. Create dir \scikitjs
2. Init npm dir "npm init"
3. Add module: yarn add scikitjs
4. error:
.....
error D:\reactapp\personal\scikitjs\node_modules\scikitjs: Command failed.
Exit code: 1
Command: (cd docs && npm install && cd ..); (npx husky install);
....

Desktop:
 - OS: Windows 10
 - Node version: v14.18.1

![Cattura](https://user-images.githubusercontent.com/1047377/150329604-5b907645-4eff-4845-bb37-ead8f08f7512.PNG)

**Comment by dcrescim** [comment]
Thanks for the report @condorman. I'll investigate and push a fix.

**Comment by dcrescim** [comment]
Hey @condorman, give it another shot and let me know if you run into any issues. I've updated the build and the latest version of the library is 1.6.0. Hopefully that solves the install issue that you've run into.

**Comment by condorman** [comment]
Thanks @dcrescim work fine!!
