### ISSUE TITLE
save and load

### ISSUE THREAD

**Issue by 1093919186** [javascriptdata/scikit.js#239]
Hi,

How do you save and then re-open a trained network?
It doesn't seem to be explained anywhere in the doc.

Thanks.

**Comment by alvgoro** [comment]
Hi @1093919186. ScikitJS does not have implemented neural network, I guess.

For saving and loading a trained "transformer" you can use toJson() and fromJson() methods.

`
// Initialize One-Hot-Encoder (whatever)
let OHE = new scikitjs.OneHotEncoder();

// Fit stage
OHE.fit(yourData);

// Save
let savedOHE = OHE.toJson()

// ...
// Your amazing code
// ...

// Load stage
// First initialize a new OHE
let newOHE = new scikitjs.OneHotEncoder();

// Then use .fromJson() method
newOHE  = newOHE.fromJson(savedOHE);
`

**Comment by 1093919186** [comment]
Hi Alvgoro, I’m grateful for your sharing. By learning the source code, I have found this implementation method. There is another issue here [issue](https://github.com/javascriptdata/scikit.js/issues/240), do you have a solution?
Thanks again.
