### ISSUE TITLE
Is this related to scikit-learn-ts?

### ISSUE THREAD

**Issue by mavavilj** [javascriptdata/scikit.js#256]
Is this related to https://github.com/transitive-bullshit/scikit-learn-ts?

If not, then how do they differ?

**Comment by steveoni** [comment]
@mavavilj same goals but different approach.

The one you mentioned use some kind of package that makes you run python packages in node version + typescript wrapper /interface.


While this repo , built sklearn algorithm from scratch and also enables importing of sklearn.py models. You can also use it on web and you can’t use sklearn-ts in the browser just in node.js runtime

**Comment by mavavilj** [comment]
So would you unbiasedly say that the scikit.js approach is better?

E.g. since it doesn't use some kind of REST abstraction between.

Or maybe they're for different use cases, because I am still struggling to understand whether one could host the ML computing on an user device (well one can, but it means more download and storage), even if it would run there vs hosting it on a server.

Or maybe ultimately a full JS/TS port enables both through a JS runtime, and then we could actually say that Python is unnecessary.

**Comment by Steve-Mcl** [comment]
> While this repo , built sklearn algorithm from scratch and also enables importing of sklearn.py models. You can also use it on web and you can’t use sklearn-ts in the browser just in node.js runtime

Hi @steveoni I cannot find any info on how to export a sklearn.py model in python and how I would then load that in a node project. Could you help please?  

Ideally a couple of snippets e.g.

```python
myDescisionTree.exportModel("modej.json") # ???
```

```js
const myDescisionTree = await _something_.importModel(jsonData or jsObject)
``` 

My apologies if I have missed this in the docs!
