### ISSUE TITLE
Any input about WASM?

### ISSUE THREAD

**Issue by mavavilj** [javascriptdata/scikit.js#257]
It seems based on Node.js currently, but there's WASM around the corner:

Any input on it w.r.t. to this project?

**Comment by dcrescim** [comment]
Hey @mavavilj! Currently this uses Tensorflow.js, which supports CPU, WASM, WebGL, and WebGPU under the hood. If you wish to use the WASM backend, just set that backend like

`tf.setBackend('wasm').then(() => {...});`

Lemme know if that doesn't make sense, and we can chat more about it.
