### ISSUE TITLE
Need Global Variable/Name-Space of scikit.js . It's more flexible to use in browser Console interactive testing/ad-hoc

### ISSUE THREAD

**Issue by LSW1980** [javascriptdata/scikit.js#259]
PREFER in HTML (as in d3.js , tensorflow.js, tfjs-vis use global variables [d3/tf/tfvis] respectively in browser console ):

<script src='src/d3.min.js'></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.0.0/dist/tf.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-vis"></script>
-------------

Then in browser console when you type tfvis. , d3. , tf. immediately a drop down list of available modules/functions
appeared right after the dot. This is faster for debugging and testing by just utilizing one script tag line in HTML!

===========================
scikit.js in HTML from your website:

<script type="module">
  import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
  import * as sk from 'https://cdn.skypack.dev/scikitjs'
  sk.setBackend(tf)
</script>
--------------------

This way sk is not recognizable in browser console. Can you provide a link/file of scikit.js  that can utilize a global
variable such as "sk" if you have one.

If scikit.js does not have this feature, will it provides one in the future [time frame please]. 

Is there a way to work around this? [create global variable "sk" and gain access to all sub
modules/functions in browser console for interactive testing].

Thank you, I'm looking forward to hear from you soon.

**Comment by ajwinkworth** [comment]
@LSW1980 have you tried:

```html
    <script type="module"> 
        import * as _tf from 'https://cdn.skypack.dev/@tensorflow/tfjs' 
        import * as _sk from 'https://cdn.skypack.dev/scikitjs' 
        _sk.setBackend(_tf)
        window.sk = _sk 
    </script>
```

Then you can access it in the console with "sk."

**Comment by LSW1980** [comment]
Thank you so much. The window.sk did the trick. This help with my transition from Python a lot. Keep up the good work!

**Comment by LSW1980** [comment]
Thank you so much. The window.sk did the trick. This help with my
transition from Python a lot. Keep up the good work!

**Comment by LSW1980** [comment]
Hi again,

Does scikit.js have a file that I can use for off-line ? with sk as a
global variable in the browser console offline?
Like: <script src=d3.js> </ script > // can work off-line in the browser
console

Most of the time people do work offline, then test apps online later. Would
you give me some options or suggestions...
I do not want to use babel or parcel to make things complicated and slow
down systems. I thought if d3, tensorflowjs, ...
can do it then scikit.js should be able to offer the same thing.

Thank you
