### ISSUE TITLE
KNeighborsRegressor

### ISSUE THREAD

**Issue by dcrescim** [javascriptdata/scikit.js#38]
Build a KNeighborsRegressor which matches the sklearn API.

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#sklearn.neighbors.KNeighborsRegressor

Technically there are 3 different strategies ‘ball_tree’, ‘kd_tree’, ‘brute’. This issue is only to support the "brute" method which checks the distance between the predicted point with *every* point in the input. 

The other two are optimizations which try to use trees (kd_tree), and spheres(ball_tree) to speed up this algo, but to start let's just do brute.

**Comment by DirkToewe** [comment]
I've been working with KD-Trees in JS [before](https://github.com/DirkToewe/nd4js/tree/master/src/spatial). Once You have implemented the `brute` version, I'd be happy to add the `kd_tree` version.

**Comment by risenW** [comment]
> I've been working with KD-Trees in JS [before](https://github.com/DirkToewe/nd4js/tree/master/src/spatial). Once You have implemented the `brute` version, I'd be happy to add the `kd_tree` version.

Hey @DirkToewe If you would love to work on this, I can pick something else. WDYT?

**Comment by DirkToewe** [comment]
Okay. It will be my first time with TypeScript and I don't yet know the best practices of `scikit.js`. But I will just try my best :smile:

**Comment by risenW** [comment]
> Okay. It will be my first time with TypeScript and I don't yet know the best practices of `scikit.js`. But I will just try my best 😄

No worries, You can read the documentation guide first: https://github.com/javascriptdata/scikit.js/blob/main/CONTRIBUTING_GUIDE.md, and also you may want to join the slack channel (@dcrescim can you share the link)- if you need any help.

**Comment by dcrescim** [comment]
Just shot over a Slack invite @DirkToewe, and invited ya to a Google Meet for Thursday. Lemme know if that time works for ya.
